In [1]:
import os
import pandas as pd

In [5]:
path = os.path.join(os.getcwd(), 'raw_data.csv')
df = pd.read_csv(path)
df

,UserName,PermissionGroupName,PermissionNameDescription,ResourceName,AccessLevelName,CompanyName
0,admin@my-company.com,Admin,Add companies,Company,add,My Company
1,admin@my-company.com,admin,Add users,Users,Add,My Company
2,admin@my-company.com,Admin,Edit companies,companies,Edit,My Company
3,admin@my-company.com,Admin,Edit users,Users,Edit,My Company
4,admin@my-company.com,Admin,Delete companies,Companies,delete,My Company
5,admin@my-company.com,Admin,Delete users,Users,Delete,My Company
6,admin@my-company.com,Admin,View companies,Companies,View,My Company
7,admin@my-company.com,Admin,View Users,users,View,My Company
8,user@my-company.com,User,Vew companies,Companies,view,My Company
9,user@my-company.com,User,View users,User,View,My Company

In [8]:
df.PermissionGroupName = df.PermissionGroupName.str.title()
df.PermissionNameDescription = df.PermissionNameDescription.str.title()
df.ResourceName = df.ResourceName.str.title()
df.AccessLevelName = df.AccessLevelName.str.title()
df.CompanyName = df.CompanyName.str.title()
df

,UserName,PermissionGroupName,PermissionNameDescription,ResourceName,AccessLevelName,CompanyName
0,admin@my-company.com,Admin,Add Companies,Company,Add,My Company
1,admin@my-company.com,Admin,Add Users,Users,Add,My Company
2,admin@my-company.com,Admin,Edit Companies,Companies,Edit,My Company
3,admin@my-company.com,Admin,Edit Users,Users,Edit,My Company
4,admin@my-company.com,Admin,Delete Companies,Companies,Delete,My Company
5,admin@my-company.com,Admin,Delete Users,Users,Delete,My Company
6,admin@my-company.com,Admin,View Companies,Companies,View,My Company
7,admin@my-company.com,Admin,View Users,Users,View,My Company
8,user@my-company.com,User,Vew Companies,Companies,View,My Company
9,user@my-company.com,User,View Users,User,View,My Company

In [ ]:
export_path = os.path.join(os.getcwd(), 'processed_data.csv')
df.to_csv(export_path)